[target.wasm32-unknown-unknown]
rustflags = [
  "-C", "target-cpu=mvp",
  "-C", "target-feature=-reference-types",
]

[target.wasm32-wasip1]
rustflags = [
  "-C", "target-cpu=mvp",
  "-C", "target-feature=-reference-types",
]

[target.wasm32-wasi]
rustflags = [
  "-C", "target-cpu=mvp",
  "-C", "target-feature=-reference-types",
]

[unstable]
build-std = ["core", "panic_abort", "alloc", "std"]
